services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    command: start
    environment:
      KC_DB: mssql
      KC_DB_URL_HOST: your-sql-host
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: sa
      KC_DB_PASSWORD: 123
      KC_DB_PORT: 1433

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
    ports:
      - "8080:8080"
